services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/data:/app/backend/data
    env_file:
      - .env
