version: "3.7"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    deploy:
      replicas: 1
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: windmill
      POSTGRES_DB: windmill
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  windmill_server:
    image: ${WM_IMAGE}
    restart: unless-stopped
    pull_policy: always
    deploy:
      replicas: 1
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=server
    depends_on:
      db:
        condition: service_healthy

  windmill_worker:
    image: ${WM_IMAGE}
    pull_policy: always
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=default
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/data/worker:/tmp/windmill/cache

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    pull_policy: always
    restart: unless-stopped
    expose:
      - 3001
    volumes:
      - .docker/data/lsp:/root/.cache

  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    volumes:
     - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:80
    environment:
      - BASE_URL=":80"
