model_list:
  - model_name: "llama3.3:70b"
    litellm_params:
      model: "ollama_chat/llama3.3:70b"
      api_base: "http://0.0.0.0:11434"

litellm_settings:
  drop_params: true

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
