services:
  nginx:
    image: nginx:1.27
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80

  app:
    image: oven/bun:latest
    command: ["bun", "/app/server.js"]
    volumes:
      - ./app/server.js:/app/server.js
    ports:
      - 3000:3000
