services:
  squid:
    image: squid
    build: ./squid
    restart: unless-stopped
    volumes:
      - ./squid/squid.conf.template:/etc/squid/squid.conf.template
      - ./squid/entrypoint.sh:/entrypoint.sh
      - ./.docker/squid/data:/srv/data
      - ./.docker/squid/logs:/srv/logs
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      - PROXY_HOST=p.webshare.io
      - PROXY_PORT=80
      - PROXY_USER=foo
      - PROXY_PASS=bar
    ports:
      - 3128:3128
