[skyvern]
configs = [
    {"env" = "local", "host" = "http://skyvern:8000/api/v1", "orgs" = [{name="Skyvern", cred="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4OTkzODA4NzMsInN1YiI6Im9fNDI0MDc1MDc4Mzg5MTU3MTcyIn0.ZyAy7yd4f7EnK8dxBFaXb0QWoD_6LBdHMuQDTKPQJHo"}]}
]
