services:
  redis:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    command: valkey-server --save "" --appendonly no

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
      - ./.docker/data:/etc/searxng/data
    environment:
      SEARXNG_REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
