version: '3.5'

services:
    app:
        image: frankapp
        build: .
        ports:
            - 8080:80
            - 8443:443
        environment:
            - CADDY_DEBUG=debug
            - DEBUG=debug
            - FRANKENPHP_CONFIG=worker /srv/public/worker.php
        volumes:
            - ./:/srv
            - ./Caddyfile:/etc/caddy/Caddyfile
